# Interactive 3D Visualization Website TEST
title: Interactive 3D Visualization Website TEST
email:
description: >- # this means to ignore newlines until "baseurl:"
  Update Later
baseurl: "/interactive" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
github_username:
analytics:

# Build settings
markdown: kramdown
remote_theme: ncar/koru-jekyll@1.0.38
plugins:
  - jekyll-feed
  - jekyll-remote-theme
  - jekyll-sitemap

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
